openapi: 3.0.0
info:
  title: Print API SQS Message Types
  version: '1.11.0'
  description: |-
    Print API SQS Message Types
    
    Whilst this is an openAPI spec, it does not imply being used to define REST APIs, nor is it intended to.
    
    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**
    
    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required 
    elements.
    
    The SQS listeners and producers in this API also consume/produce an optional x-correlation-id header that can be used
    to trace requests.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/send-application-to-print':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendApplicationToPrintMessage'
      responses:
        '204':
          description: No response content.
  '/process-print-request-batch':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/ProcessPrintRequestBatchMessage'
      responses:
        '204':
          description: No response content.
  '/process-print-response-file':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/ProcessPrintResponseFileMessage'
      responses:
        '204':
          description: No response content.
  '/process-print-response':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/ProcessPrintResponseMessage'
      responses:
        '204':
          description: No response content.

  '/application-removed':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/ApplicationRemovedMessage'
      responses:
        '204':
          description: No response content.

  '/remove-certificate':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/RemoveCertificateMessage'
      responses:
        '204':
          description: No response content.

components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:

    SendApplicationToPrintMessage:
      description: The SQS message for sending an application to print.
      type: object
      properties:
        sourceReference:
          type: string
          description: Reference in the source application that this print request relates to
        applicationReference:
          type: string
          description: The application reference as known by the citizen. Not guaranteed to be unique.
        sourceType:
          $ref: '#/components/schemas/SourceType'
        gssCode:
          type: string
          minLength: 9
          maxLength: 9
          description: GSS code of the ERO responsible for sending the message
        requestDateTime:
          type: string
          format: date-time
          description: The date time the Voter Authority Certificate print request was requested
          example: '2022-06-02T13:20:01.000Z'
        applicationReceivedDateTime:
          type: string
          format: date-time
          description: The date time the Voter Authority Certificate application was received (e.g. from IER or in the post). Not to be confused with the date time the voter card application was created within the system.
          example: '2022-06-01T00:00:00.000Z'
        firstName:
          type: string
          maxLength: 255
          description: First name of the Elector
          example: John
        middleNames:
          type: string
          maxLength: 255
          description: Middle names of the Elector
          example: Malcolm
        surname:
          type: string
          maxLength: 255
          description: Surname of the Elector
          example: Smith
        certificateLanguage:
          $ref: '#/components/schemas/CertificateLanguage'
        supportingInformationFormat:
          $ref: '#/components/schemas/SupportingInformationFormat'
        photoLocation:
          type: string
          description: The location of the Elector's photo. Typically an S3 ARN
          maxLength: 1024
        delivery:
          $ref: '#/components/schemas/CertificateDelivery'
        userId:
          type: string
          format: email
          maxLength: 1024
          description: The userId (email address) of the EROP user requesting the print
          example: fred.bloggs@some-domain.co.uk
      required:
        - sourceReference
        - sourceType
        - applicationReference
        - requestDateTime
        - applicationReceivedDateTime
        - firstName
        - surname
        - certificateLanguage
        - supportingInformationFormat
        - photoLocation
        - delivery
        - userId

    ApplicationRemovedMessage:
      description: The SQS message sent when the source application is removed from the originating system.
      type: object
      properties:
        sourceReference:
          type: string
          description: Reference in the source application.
        sourceType:
          $ref: '#/components/schemas/SourceType'
        gssCode:
          type: string
          minLength: 9
          maxLength: 9
          description: GSS code of the ERO responsible for sending the message
      required:
        - sourceReference
        - sourceType
        - gssCode

    RemoveCertificateMessage:
      title: RemoveCertificateMessage
      description: The SQS message sent to remove an individual Certificate record from the database and its corresponding photo from S3.
      type: object
      properties:
        certificateId:
          type: string
          format: uuid
          description: The id (primary key) of the Certificate row
        certificatePhotoArn:
          type: string
          description: The Certificate photo's S3 arn
      required:
        - certificateId
        - certificatePhotoArn

    SourceType:
      title: SourceType
      description: An enumeration of sources for this print request
      type: string
      enum:
        - voter-card
        - anonymous-elector-document

    CertificateLanguage:
      title: CertificateLanguage
      description: The Voter Authority Certificate language
      type: string
      enum:
        - cy
        - en
      default: en

    SupportingInformationFormat:
      type: string
      description: The format of the supporting information sent with the Voter Authority Certificate.
      enum:
        - standard
        - braille
        - large-print
        - easy-read

    CertificateDelivery:
      title: CertificateDelivery
      description: Object describing how and where the Voter Authority Certificate should be delivered
      type: object
      properties:
        deliveryClass:
          $ref: '#/components/schemas/DeliveryClass'
        deliveryAddressType:
          $ref: '#/components/schemas/DeliveryAddressType'
        addressee:
          type: string
          maxLength: 255
          description: The addressee to be printed in addition to the delivery address
        address:
          $ref: '#/components/schemas/Address'
        addressFormat:
          $ref: '#/components/schemas/AddressFormat'
      required:
        - deliveryClass
        - deliveryAddressType
        - addressee
        - address
        - addressFormat

    DeliveryClass:
      title: DeliveryClass
      description: The delivery class for the Voter Authority Certificate
      type: string
      enum:
        - standard

    DeliveryAddressType:
      title: DeliveryAddressType
      description: The delivery address type for the Voter Authority Certificate
      type: string
      enum:
        - registered
        - ero-collection
        - alternative

    Address:
      title: Address
      description: Address format used throughout gov.uk voter services.
      type: object
      x-examples:
        Minimum data:
          street: Street 1
          postcode: PC1 2FB
        Normal Address:
          street: East Lodge
          property: Balruddery
          locality: Invergowrie
          town: Dundee
          area: Angus
          postcode: DD25LF
          uprn: '117095813'
      properties:
        street:
          type: string
          maxLength: 255
        property:
          type: string
          maxLength: 255
        locality:
          type: string
          maxLength: 255
        town:
          type: string
          maxLength: 255
        area:
          type: string
          maxLength: 255
        postcode:
          type: string
          maxLength: 10
        uprn:
          type: string
          description: Unique Property Reference Number consisting of up to 12 digits in length
          pattern: '^\d{1,12}$'
      required:
        - street
        - postcode

    AddressFormat:
      title: AddressFormat
      description: Enumeration of address formats
      type: string
      enum:
        - uk
        - overseas
        - bfpo

    ProcessPrintRequestBatchMessage:
      description: The SQS message for processing a batch of print requests
      type: object
      properties:
        batchId:
          type: string
          description: The batch ID
        printRequestCount:
          type: integer
          description: The number of print requests included in the batch
      required:
        - batchId

    ProcessPrintResponseFileMessage:
      description: The SQS message for processing a print response file
      type: object
      properties:
        directory:
          type: string
          description: The directory where file to be processed is present
        fileName:
          type: string
          description: The file name to be processed
      required:
        - directory
        - fileName

    ProcessPrintResponseMessage:
      description: The SQS message for processing the status change for an individual Print Request
      type: object
      properties:
        requestId:
          type: string
          description: |-
            The unique identifier of the Print Request
            A 24 character hex string
          example: 14ab70e8bd3b400fbd95246c
        timestamp:
          type: string
          format: date-time
          description: The date time the Print Provider issued this status change for the Print Request.
          example: '2022-06-01T14:23:03.000Z'
        statusStep:
          type: string
          description: The current print step this update relates to
          enum:
            - PROCESSED
            - IN-PRODUCTION
            - PRINTED
            - DISPATCHED
            - NOT-DELIVERED
        status:
          type: string
          enum:
            - SUCCESS
            - FAILED
          description: Indicates if the step change was successful or not.
        issueDate:
          type: string
          format: date
          description: |-
            Only returned if statusStep is PRINTED. This is returned for both initial print requests and re-prints.
            This is the legal issuedDate.
          example: '2022-06-01'
        suggestedExpiryDate:
          type: string
          format: date
          description: |-
            Only returned if statusStep is PRINTED. This is returned for both initial print requests and re-prints.
            This is the legal issuedDate + 10 years.
          example: '2032-06-01'
        message:
          type: string
          maxLength: 255
          description: Error description. Only populated if `status` is `FAILED`
      required:
        - requestId
        - timestamp
        - statusStep
        - status

  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses: { }

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    SendApplicationToPrintMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendApplicationToPrintMessage'
    ProcessPrintRequestBatchMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcessPrintRequestBatchMessage'
    ProcessPrintResponseFileMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcessPrintResponseFileMessage'
    ProcessPrintResponseMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcessPrintResponseMessage'
    ApplicationRemovedMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationRemovedMessage'
    RemoveCertificateMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RemoveCertificateMessage'
