@startuml

title EROP Print Sequence

participant EROP
participant "EROP Print Service SQS Queue"
participant "EROP Print Service"
participant "EROP Print Service Database"
participant "Print SFTP Server"
participant "Print Service"


EROP->"EROP Print Service SQS Queue": Send Approved Applications
activate "EROP Print Service SQS Queue"
"EROP Print Service SQS Queue"->"EROP Print Service": Pull Approved Applications
deactivate "EROP Print Service SQS Queue"
activate "EROP Print Service"
"EROP Print Service"->"EROP Print Service Database": Store Approved Application Request
deactivate "EROP Print Service"

loop Cron Batch Process (Every x Mins)
    "EROP Print Service"<-"EROP Print Service Database": Retrieve Current Approved Request Batch
    activate "EROP Print Service"
    "EROP Print Service"->"EROP Print Service": Zip/Format Batch - Array[PrintRequest]
    "EROP Print Service"->"Print SFTP Server": Send Batch - Array[PrintRequest]
    deactivate "EROP Print Service"
end loop

loop Cron Batch Process (Every x Mins)
    "Print Service"<-"Print SFTP Server": Retrieve Print Batches - Array[PrintRequest]
    activate "Print Service"
end loop

loop Print Sevice Processes
    "Print Service"->"Print Service": Process Print Requests - Array[PrintRequest]
    "Print Service"->"Print Service": Zip/Format Batch Status Updates - Array[PrintRequestStatusUpdate]
    "Print Service"->"Print SFTP Server": Send Print Requests Status Updates - Array[PrintRequestStatusUpdate]
    deactivate "Print Service"
end loop

loop Cron Batch Process (Every x Mins)
    "EROP Print Service"<-"Print SFTP Server": Retrieve Print Status Updates - Array[PrintRequestStatusUpdate]
    activate "EROP Print Service"
    "EROP Print Service"->"EROP Print Service Database": Update Print Request Statuses
    deactivate "EROP Print Service"
end loop

"EROP"->"EROP Print Service": Get Print Request Statuses API
activate "EROP"
activate "EROP Print Service"
"EROP Print Service"->"EROP Print Service Database": Get Print Request Statuses
activate "EROP Print Service Database"
"EROP Print Service"<-"EROP Print Service Database": Return Print Request Statuses
deactivate "EROP Print Service Database"
"EROP Print Service"->"EROP": Return Print Requests Statuses API
deactivate "EROP Print Service"
deactivate "EROP"


@enduml