
email:
  client:
    sender: noreply_test_erouser@erop.ierds.uk
    allow-list-enabled: true
    allow-list-domains:
      - valtech.com
      - levellingup.gov.uk
      - softwire.com
  content:
    portal-base-url: https://ero.test.erop.ierds.uk
    certificate-returned:
      email-body-template: email-templates/certificate-returned-la-emails.html
      send-to-requesting-user: true
