jobs:
  remove-vca-initial-retention-period-data:
    name: "RemoveVcaInitialRetentionPeriodData"
    cron: "0 1/10 * ? * *" # every 10 minutes starting at :01
  remove-aed-initial-retention-period-data:
    name: "RemoveAedInitialRetentionPeriodData"
    cron: "0 2/10 * ? * *" # every 10 minutes starting at :02
  remove-vca-final-retention-period-data:
    name: "RemoveVcaFinalRetentionPeriodData"
    cron: "0 5/10 * ? * *" # every 10 minutes starting at :05
  remove-aed-final-retention-period-data:
    name: "RemoveAedFinalRetentionPeriodData"
    cron: "0 5/10 * ? * *" # every 10 minutes starting at :05

email:
  client:
    sender: noreply_int_erouser@erop.ierds.uk
    allow-list-enabled: true
    allow-list-domains:
      - valtech.com
      - levellingup.gov.uk
      - softwire.com
  content:
    portal-base-url: https://ero.int.erop.ierds.uk
    certificate-returned:
      email-body-template: email-templates/certificate-returned-la-emails.html
      send-to-requesting-user: true
