jobs:
  remove-vca-initial-retention-period-data:
    name: "RemoveVcaInitialRetentionPeriodData"
    cron: "0 */10 * ? * *" # every 10 minutes
  remove-vca-final-retention-period-data:
    name: "RemoveVcaFinalRetentionPeriodData"
    cron: "0 */10 * ? * *" # every 10 minutes
