spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/print_application
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 20 # max pool size and min-idle deliberately sized to cater for extreme volume and load
      minimum-idle: 10

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

sqs:
  send-application-to-print-queue-name: ${SQS_SEND_APPLICATION_TO_PRINT_QUEUE_NAME}
  process-print-request-batch-queue-name: ${SQS_PROCESS_PRINT_REQUEST_BATCH_QUEUE_NAME}
  process-print-response-file-queue-name: ${SQS_PROCESS_PRINT_RESPONSE_FILE_QUEUE_NAME}
  process-print-response-queue-name: ${SQS_PROCESS_PRINT_RESPONSE_QUEUE_NAME}
  application-removed-queue-name: ${SQS_APPLICATION_REMOVED_QUEUE_NAME}

api:
  print-api:
    generate-temporary-certificate:
      valid-on-date:
        max-calendar-days-in-future: 30
    retention.period:
      certificate-initial-retention-period: "P28D" # 28 working days
  ero-management:
    url: ${API_ERO_MANAGEMENT_URL}

sftp:
  host: ${SFTP_HOST}
  user: ${SFTP_USER}
  password: ${SFTP_PASSWORD}
  private-key: ${SFTP_PRIVATE_KEY}
  print-request-upload-directory: ${SFTP_PRINT_REQUEST_UPLOAD_DIRECTORY}
  print-response-download-directory: ${SFTP_PRINT_RESPONSE_DOWNLOAD_DIRECTORY}

jobs:
  enabled: true
  lock-at-most-for: "PT10M"
  batch-print-requests:
    name: "BatchPrintRequests"
    cron: "0 0/15 * * * *" # every 15 minutes, starting on the hour - see analysis and recommendations in EIP1-2515
    batch-size: 50
    max-un-batched-records: 5000 # see analysis and recommendations in EIP1-2885
    daily-limit: 150_000
  process-print-responses:
    name: "ProcessPrintResponses"
    cron: "0 15/30 * * * *" # every 30 minutes starting at 15 minutes past the hour - see analysis and recommendations in EIP1-2515

temporary-certificate:
  certificate-pdf:
    english:
      path: "classpath:temporary-certificate-template/Temp Voter Authority Certificate (English).pdf"
      placeholder:
        elector-name: "applicant-name"
        local-authority-name-en: "local-authority-name-en"
        date-of-issue: "date-issued"
        valid-on-date: "date-valid"
        certificate-number: "certificate-number"
      images:
        voter-photo: # Position the top-left corner of the image measured in mm from the page origin in the bottom-left
          absolute-x-mm: 21.6
          absolute-y-mm: 201.6
          fit-width-mm: 35
          fit-height-mm: 45
    welsh:
      path: "classpath:temporary-certificate-template/Temp Voter Authority Certificate (Bilingual).pdf"
      placeholder:
        elector-name: "applicant-name"
        local-authority-name-en: "local-authority-name-en"
        local-authority-name-cy: "local-authority-name-cy"
        date-of-issue: "date-issued"
        valid-on-date: "date-valid"
        certificate-number: "certificate-number"
      images:
        voter-photo: # Position the top-left corner of the image measured in mm from the page origin in the bottom-left
          absolute-x-mm: 21.6
          absolute-y-mm: 194.6
          fit-width-mm: 35
          fit-height-mm: 45
  explainer-pdf:
    english:
      path: "classpath:temporary-certificate-template/Explainer Document (English).pdf"
      placeholder:
        ero-name: "ero-recipient"
        ero-address-line1: "ero-address-1-en"
        ero-address-line2: "ero-address-2-en"
        ero-address-line3: "ero-address-3-en"
        ero-address-line4: "ero-address-4-en"
        ero-address-postcode: "ero-postcode-en"
        ero-email: "ero-email-en"
        ero-phone: "ero-phonenumber-en"
    welsh:
      path: "classpath:temporary-certificate-template/Explainer Document (Dual Language).pdf"
      placeholder:
        ero-name: "ero-recipient"
        ero-address-line1: "ero-address-1-cy"
        ero-address-line2: "ero-address-2-cy"
        ero-address-line3: "ero-address-3-cy"
        ero-address-line4: "ero-address-4-cy"
        ero-address-postcode: "ero-postcode-cy"
        ero-email: "ero-email-cy"
        ero-phone: "ero-phonenumber-cy"

thread-pool:
  zip:
    core-size: 5
    max-size: 5

logging:
  pattern:
    level: "%X{correlationId}%5p"
  level:
    com:
      jcraft:
        jsch: WARN
