jobs:
  remove-vca-initial-retention-period-data:
    name: "RemoveVcaInitialRetentionPeriodData"
    cron: "0 1/10 * ? * *" # every 10 minutes starting at :01
  remove-aed-initial-retention-period-data:
    name: "RemoveAedInitialRetentionPeriodData"
    cron: "0 2/10 * ? * *" # every 10 minutes starting at :02
  remove-vca-final-retention-period-data:
    name: "RemoveVcaFinalRetentionPeriodData"
    cron: "0 5/10 * ? * *" # every 10 minutes starting at :05
  remove-aed-final-retention-period-data:
    name: "RemoveAedFinalRetentionPeriodData"
    cron: "0 5/10 * ? * *" # every 10 minutes starting at :05

email:
  client:
    sender: noreply_int_erouser@erop.ierds.uk
    allow-list-enabled: true
    allow-list-domains:
      - valtech.com
      - levellingup.gov.uk
      - softwire.com
  content:
    certificate-returned:
      email-body-template: email-templates/non-prod/certificate-returned.html
      send-to-requesting-user: true
    certificate-failed-to-print:
      email-body-template: email-templates/non-prod/certificate-failed-to-print.html
      send-to-requesting-user: true
