name: Build image and deploy to dev

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get latest patch version tag for minor version
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cabinetoffice/eip-ero-print-api

      - name: Bump version tag
        uses: cabinetoffice/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: Push version tag
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${{ github.event.head_commit.message }}"
          git push origin "${tag}"

  build-and-push:
    needs: tag
    uses: ./.github/workflows/build-and-push.yml
    with:
      version: ${{ needs.tag.outputs.version }}
    secrets: inherit

  deploy:
    needs:
      - tag
      - build-and-push
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: dev
      version: ${{ needs.tag.outputs.version }}
    secrets: inherit
