name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/dependency-submission.yml@eip1-13829-use-read-only-rule-and-avoid-dev2-environment-on-main
    secrets: inherit
