name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/dependency-submission.yml@main
    secrets: inherit
