name: Deploy a tagged version to an environment

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - sb
          - dev
          - int
          - pvt
          - test
          - live
          - dev2
          - int2
          - test2
          - beta

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: ${{inputs.deploy_environment}}
      version: ${{github.ref_name}}
    secrets: inherit
